# Generated by Django 5.0.7 on 2024-08-20 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarparkRates',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('carparkcode', models.CharField(max_length=255)),
                ('carparkname', models.CharField(max_length=255)),
                ('vehcat', models.CharField(max_length=255)),
                ('starttime', models.TimeField()),
                ('endtime', models.TimeField()),
                ('weekdayrate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('weekdaymin', models.IntegerField()),
                ('satdayrate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('satdaymin', models.IntegerField()),
                ('sunphrate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sunphmin', models.IntegerField()),
                ('parkingsystem', models.CharField(max_length=255)),
                ('carparkcapacity', models.IntegerField()),
                ('geometries', models.JSONField()),
            ],
            options={
                'db_table': 'carpark_rates',
            },
        ),
    ]
